//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatRent.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlatrentEntities : DbContext
    {
        public FlatrentEntities()
            : base("name=FlatrentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<flat> flats { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<roomcount> roomcounts { get; set; }
        public DbSet<wallmaterial> wallmaterials { get; set; }
        public DbSet<yearconstruction> yearconstructions { get; set; }
    }
}
