//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatRent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class flat
    {
        public int id { get; set; }
        public Nullable<int> idRegion { get; set; }
        public Nullable<int> idRoomCount { get; set; }
        public Nullable<int> idWallMaterial { get; set; }
        public Nullable<int> idYearConstruction { get; set; }
        public Nullable<int> floor { get; set; }
        public Nullable<int> numberOfFloors { get; set; }
        public Nullable<float> square { get; set; }
        public string street { get; set; }
        public Nullable<int> houseNumber { get; set; }
        public Nullable<int> flatNumber { get; set; }
        public Nullable<int> views { get; set; }
    
        public virtual region region { get; set; }
        public virtual roomcount roomcount { get; set; }
        public virtual wallmaterial wallmaterial { get; set; }
        public virtual yearconstruction yearconstruction { get; set; }
    }
}
