//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatRent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yearconstruction
    {
        public yearconstruction()
        {
            this.flats = new HashSet<flat>();
        }
    
        public int id { get; set; }
        public Nullable<int> yearConstruction { get; set; }
        public Nullable<int> coefficient { get; set; }
    
        public virtual ICollection<flat> flats { get; set; }
    }
}
